/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.derby;

import org.springframework.boot.SpringApplication;

public class App {
	
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
