/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package base;

import org.junit.jupiter.api.Test;

import base.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
    }
}
